name: ci workflow
on:
    push:
jobs:
    build: # it a name of the job
        runs-on: ubuntu-latest #gitlab-runner-free
        steps:
            - uses: actions/checkout@v4 #clone the code into ubuntu server
            - uses: docker/setup-buildx-action@v4 #build an app via docker



